### All
GET http://localhost:3000/api/event-bus/consume?subscribers=*&limit=50
Authorization: Bearer c0d3ly-3v3nt-bus-s3cr3t-k3y

### codely.retention.send_welcome_email_on_user_registered
GET http://localhost:3000/api/event-bus/consume?subscribers=codely.retention.send_welcome_email_on_user_registered&limit=50
Authorization: Bearer c0d3ly-3v3nt-bus-s3cr3t-k3y

### codely.shop.register_shop_user_on_user_registered
GET http://localhost:3000/api/event-bus/consume?subscribers=codely.shop.register_shop_user_on_user_registered&limit=50
Authorization: Bearer c0d3ly-3v3nt-bus-s3cr3t-k3y
